app:
  boundedcontext: b1
  domain: d1
  microservice: ${spring.application.name}
  subdomain: sb1
server:
  error:
    include-binding-errors: always
    include-message: always
  port: ${app.port:10000}
  tomcat:
    threads:
      max: 200
      min-spare: 20
    max-connections: 500
    max-keep-alive-requests: 300
    keep-alive-timeout: 120000
spring:
  application:
    name: order
  cloud:
    loadbalancer:
      retry:
        avoid-previous-instance: true
        enabled: false
        max-retries-on-next-service-instance: 2
        max-retries-on-same-service-instance: 0
        retry-on-all-operations: true
  config:
    import: configserver:http://127.0.0.1:8888
resilience4j:
  retry:
    metrics:
      enabled: true
    instances:
      restaurant-menu:
        max-attempts: 2
        wait-duration: 10ms
        retry-exception-predicate: com.training.spring.order.retry.RestaurantMenuRetryExceptionHandler
        result-predicate: com.training.spring.order.retry.RestaurantMenuResultHandler

        